# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed2974f0e70245a0698e5079b50f5756e6728df76d86a54f7961d7d49698b5d24620380ceefb46f66996eb1f8683bfc63b5c73f15faf575dfefc96d183d37d29

test:
  secret_key_base: 99af4cb8df5fd6678482dc97f857952c21d5352f875cfa70d4b540b45fee8fd1a6a9d3338ac06aeb47fce269b8630bde07c6ae959e2f8b4cc1a3a66edfd6d592

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
